// Auto-generated canonical entity dictionary for SIH Intelligence Platform
export interface CanonicalEntity { id: string; name: string; type: string; subtitle: string; riskScore: number; }

export const CANONICAL_ENTITIES: Record<string, CanonicalEntity> = {
  'P001': { id: 'P001', name: 'Sneha Chawla', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P002': { id: 'P002', name: 'Anirudh Naidu', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P003': { id: 'P003', name: 'Garima Bhattacharya', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P004': { id: 'P004', name: 'Omkar Rajagopalan', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P005': { id: 'P005', name: 'Rashi Unnikrishnan', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P006': { id: 'P006', name: 'Sanjit Ansari', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P007': { id: 'P007', name: 'Monika Vaidyanathan', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P008': { id: 'P008', name: 'Sudhir Bansal', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P009': { id: 'P009', name: 'Mandira Raina', type: 'PERSON', subtitle: 'Noida', riskScore: 75 },
  'P010': { id: 'P010', name: 'Manav Kelkar', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P011': { id: 'P011', name: 'Surekha Bhardwaj', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P012': { id: 'P012', name: 'Vihaan Dutta', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P013': { id: 'P013', name: 'Parineeti Gupta', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P014': { id: 'P014', name: 'Anand Khanna', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P015': { id: 'P015', name: 'Sonali Raghavan', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P016': { id: 'P016', name: 'Mayank Upadhyay', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P017': { id: 'P017', name: 'Payal Menon', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P018': { id: 'P018', name: 'Uday Sanyal', type: 'PERSON', subtitle: 'Delhi', riskScore: 75 },
  'P019': { id: 'P019', name: 'Konkona Shankar', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P020': { id: 'P020', name: 'Shailesh Arora', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P021': { id: 'P021', name: 'Shalini Gopalan', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P022': { id: 'P022', name: 'Ajay Kumar', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P023': { id: 'P023', name: 'Neerja Choudhury', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P024': { id: 'P024', name: 'Vinay Mohapatra', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P025': { id: 'P025', name: 'Konkana Saini', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P026': { id: 'P026', name: 'Madhav Pandey', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P027': { id: 'P027', name: 'Kali Banerjee', type: 'PERSON', subtitle: 'Gurugram', riskScore: 75 },
  'P028': { id: 'P028', name: 'Suraj Kulkarni', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P029': { id: 'P029', name: 'Dia Mehta', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P030': { id: 'P030', name: 'Akash Swamy', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P031': { id: 'P031', name: 'Esha Gopalakrishnan', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P032': { id: 'P032', name: 'Himanshu Anantharaman', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P033': { id: 'P033', name: 'Kareena Bhandari', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P034': { id: 'P034', name: 'Mahesh Subramaniam', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P035': { id: 'P035', name: 'Divya Subramanian', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P036': { id: 'P036', name: 'Krishna Vohra', type: 'PERSON', subtitle: 'Ghaziabad', riskScore: 75 },
  'P037': { id: 'P037', name: 'Geeta Behera', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P038': { id: 'P038', name: 'Umesh Gokhale', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P039': { id: 'P039', name: 'Madhavi Mohammad', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P040': { id: 'P040', name: 'Kartik Tiwari', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P041': { id: 'P041', name: 'Archana Chatterjee', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P042': { id: 'P042', name: 'Pratik Krishnamurthy', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P043': { id: 'P043', name: 'Tarini Gupta', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P044': { id: 'P044', name: 'Chandan Dhawan', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'P045': { id: 'P045', name: 'Leela Aggarwal', type: 'PERSON', subtitle: 'Faridabad', riskScore: 75 },
  'PH003': { id: 'PH003', name: '+91 98773-97255 (Garima\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH010': { id: 'PH010', name: '+91 74989-60600 (Surekha\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH004': { id: 'PH004', name: '+91 78752-70817 (Omkar\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH029': { id: 'PH029', name: '+91 78752-70817 (Suraj\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH020': { id: 'PH020', name: '+91 83662-78794 (Ajay\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH021': { id: 'PH021', name: '+91 83662-78794 (Vinay\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH001': { id: 'PH001', name: '+91 96256-63408 (Monika\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH002': { id: 'PH002', name: '+91 96634-85507 (Garima\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH005': { id: 'PH005', name: '+91 77244-27023 (Rashi\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH006': { id: 'PH006', name: '+91 79139-31238 (Mandira\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH007': { id: 'PH007', name: '+91 87386-09388 (Anirudh\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH008': { id: 'PH008', name: '+91 94749-18827 (Mandira\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH009': { id: 'PH009', name: '+91 74300-75289 (Sonali\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH011': { id: 'PH011', name: '+91 85004-72902 (Surekha\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH012': { id: 'PH012', name: '+91 97849-34389 (Surekha\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH013': { id: 'PH013', name: '+91 72001-77038 (Anand\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH014': { id: 'PH014', name: '+91 85294-69534 (Manav\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH015': { id: 'PH015', name: '+91 87468-19792 (Payal\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH016': { id: 'PH016', name: '+91 70626-56326 (Payal\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH017': { id: 'PH017', name: '+91 77781-72697 (Shailesh\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH018': { id: 'PH018', name: '+91 76946-91821 (Madhav\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH019': { id: 'PH019', name: '+91 82851-80304 (Shailesh\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH022': { id: 'PH022', name: '+91 96058-48253 (Neerja\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH023': { id: 'PH023', name: '+91 98395-50588 (Konkana\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH024': { id: 'PH024', name: '+91 72182-53940 (Vinay\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH025': { id: 'PH025', name: '+91 95638-49944 (Krishna\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH026': { id: 'PH026', name: '+91 87376-90322 (Kareena\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH027': { id: 'PH027', name: '+91 87739-06242 (Kareena\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH028': { id: 'PH028', name: '+91 97174-58620 (Divya\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH030': { id: 'PH030', name: '+91 99164-51186 (Dia\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH031': { id: 'PH031', name: '+91 81225-39345 (Esha\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH032': { id: 'PH032', name: '+91 79680-61618 (Suraj\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH033': { id: 'PH033', name: '+91 98211-30848 (Geeta\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH034': { id: 'PH034', name: '+91 86981-24599 (Geeta\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH035': { id: 'PH035', name: '+91 75023-36752 (Geeta\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH036': { id: 'PH036', name: '+91 80995-04984 (Pratik\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH037': { id: 'PH037', name: '+91 76074-55893 (Archana\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH038': { id: 'PH038', name: '+91 99138-58614 (Umesh\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH039': { id: 'PH039', name: '+91 89255-41318 (Umesh\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'PH040': { id: 'PH040', name: '+91 92814-69679 (Leela\'s Phone)', type: 'PHONE', subtitle: 'PHONE', riskScore: 60 },
  'VH02': { id: 'VH02', name: 'Hyundai i20 (UP16-AA-1646)', type: 'VEHICLE', subtitle: 'Hyundai i20', riskScore: 65 },
  'VH05': { id: 'VH05', name: 'Maruti Swift (DL01-WQ-8995)', type: 'VEHICLE', subtitle: 'Maruti Swift', riskScore: 65 },
  'VH11': { id: 'VH11', name: 'Bajaj Pulsar (UP14-YH-6937)', type: 'VEHICLE', subtitle: 'Bajaj Pulsar', riskScore: 65 },
  'VH17': { id: 'VH17', name: 'Tata Ace (DL09-DC-4652)', type: 'VEHICLE', subtitle: 'Tata Ace', riskScore: 65 },
  'VH01': { id: 'VH01', name: 'Maruti Alto (UP16-KL-0246)', type: 'VEHICLE', subtitle: 'Maruti Alto', riskScore: 65 },
  'VH03': { id: 'VH03', name: 'Honda Activa (UP16-QD-5347)', type: 'VEHICLE', subtitle: 'Honda Activa', riskScore: 65 },
  'VH04': { id: 'VH04', name: 'Royal Enfield Classic (DL01-UX-5951)', type: 'VEHICLE', subtitle: 'Royal Enfield Classic', riskScore: 65 },
  'VH06': { id: 'VH06', name: 'Maruti Alto (DL01-XU-8740)', type: 'VEHICLE', subtitle: 'Maruti Alto', riskScore: 65 },
  'VH07': { id: 'VH07', name: 'Maruti Alto (HR26-EP-0427)', type: 'VEHICLE', subtitle: 'Maruti Alto', riskScore: 65 },
  'VH08': { id: 'VH08', name: 'Tata Ace (HR26-KX-1002)', type: 'VEHICLE', subtitle: 'Tata Ace', riskScore: 65 },
  'VH09': { id: 'VH09', name: 'TVS Jupiter (HR26-BN-3197)', type: 'VEHICLE', subtitle: 'TVS Jupiter', riskScore: 65 },
  'VH10': { id: 'VH10', name: 'Mahindra Bolero (UP14-DM-1748)', type: 'VEHICLE', subtitle: 'Mahindra Bolero', riskScore: 65 },
  'VH12': { id: 'VH12', name: 'Bajaj Pulsar (UP14-XT-3969)', type: 'VEHICLE', subtitle: 'Bajaj Pulsar', riskScore: 65 },
  'VH13': { id: 'VH13', name: 'Honda Activa (HR29-VW-7750)', type: 'VEHICLE', subtitle: 'Honda Activa', riskScore: 65 },
  'VH14': { id: 'VH14', name: 'Honda Activa (HR29-MK-8341)', type: 'VEHICLE', subtitle: 'Honda Activa', riskScore: 65 },
  'VH15': { id: 'VH15', name: 'Maruti Swift (HR29-PH-1718)', type: 'VEHICLE', subtitle: 'Maruti Swift', riskScore: 65 },
  'VH16': { id: 'VH16', name: 'Toyota Innova (DL09-LY-9880)', type: 'VEHICLE', subtitle: 'Toyota Innova', riskScore: 65 },
  'VH18': { id: 'VH18', name: 'Mahindra Bolero (DL09-HF-2764)', type: 'VEHICLE', subtitle: 'Mahindra Bolero', riskScore: 65 },
  'LOC01': { id: 'LOC01', name: 'Crescent Mall', type: 'LOCATION', subtitle: 'Noida', riskScore: 45 },
  'LOC02': { id: 'LOC02', name: 'Palm Court Hotel', type: 'LOCATION', subtitle: 'Noida', riskScore: 45 },
  'LOC03': { id: 'LOC03', name: 'City Office Tower', type: 'LOCATION', subtitle: 'Noida', riskScore: 45 },
  'LOC04': { id: 'LOC04', name: 'Highway Dhaba', type: 'LOCATION', subtitle: 'Delhi', riskScore: 45 },
  'LOC05': { id: 'LOC05', name: 'Crescent Mall', type: 'LOCATION', subtitle: 'Delhi', riskScore: 45 },
  'LOC06': { id: 'LOC06', name: 'Old Bus Depot', type: 'LOCATION', subtitle: 'Delhi', riskScore: 45 },
  'LOC07': { id: 'LOC07', name: 'Lakeside Residency', type: 'LOCATION', subtitle: 'Gurugram', riskScore: 45 },
  'LOC08': { id: 'LOC08', name: 'Crescent Mall', type: 'LOCATION', subtitle: 'Gurugram', riskScore: 45 },
  'LOC09': { id: 'LOC09', name: 'Blue Moon Restaurant', type: 'LOCATION', subtitle: 'Gurugram', riskScore: 45 },
  'LOC10': { id: 'LOC10', name: 'Central Market', type: 'LOCATION', subtitle: 'Ghaziabad', riskScore: 45 },
  'LOC11': { id: 'LOC11', name: 'Riverside Warehouse', type: 'LOCATION', subtitle: 'Ghaziabad', riskScore: 45 },
  'LOC12': { id: 'LOC12', name: 'Palm Court Hotel', type: 'LOCATION', subtitle: 'Ghaziabad', riskScore: 45 },
  'LOC13': { id: 'LOC13', name: 'Lakeside Residency', type: 'LOCATION', subtitle: 'Faridabad', riskScore: 45 },
  'LOC14': { id: 'LOC14', name: 'Freight Yard', type: 'LOCATION', subtitle: 'Faridabad', riskScore: 45 },
  'LOC15': { id: 'LOC15', name: 'Riverside Warehouse', type: 'LOCATION', subtitle: 'Faridabad', riskScore: 45 },
  'LOC16': { id: 'LOC16', name: 'Transnational Freight Warehouse', type: 'LOCATION', subtitle: 'Delhi', riskScore: 45 },
  'LOC17': { id: 'LOC17', name: 'Central Interstate Bus Terminal', type: 'LOCATION', subtitle: 'Delhi', riskScore: 45 },
  'LOC18': { id: 'LOC18', name: 'Grand Junction Hotel', type: 'LOCATION', subtitle: 'Gurugram', riskScore: 45 },
  'ORG01': { id: 'ORG01', name: 'Sector18 Logistics Pvt Ltd', type: 'ORGANIZATION', subtitle: 'Noida', riskScore: 75 },
  'ORG02': { id: 'ORG02', name: 'Silverline Traders Association', type: 'ORGANIZATION', subtitle: 'Noida', riskScore: 75 },
  'ORG03': { id: 'ORG03', name: 'Riverside Transport Co', type: 'ORGANIZATION', subtitle: 'Delhi', riskScore: 75 },
  'ORG04': { id: 'ORG04', name: 'Blue Delta Enterprises', type: 'ORGANIZATION', subtitle: 'Delhi', riskScore: 75 },
  'ORG05': { id: 'ORG05', name: 'Northside Financial Services', type: 'ORGANIZATION', subtitle: 'Gurugram', riskScore: 75 },
  'ORG06': { id: 'ORG06', name: 'Greenfield Warehousing', type: 'ORGANIZATION', subtitle: 'Gurugram', riskScore: 75 },
  'ORG07': { id: 'ORG07', name: 'Eastgate Freight Company', type: 'ORGANIZATION', subtitle: 'Ghaziabad', riskScore: 75 },
  'ORG08': { id: 'ORG08', name: 'Crestview Holdings', type: 'ORGANIZATION', subtitle: 'Ghaziabad', riskScore: 75 },
  'ORG09': { id: 'ORG09', name: 'Old Quarter Traders Circle', type: 'ORGANIZATION', subtitle: 'Faridabad', riskScore: 75 },
  'ORG10': { id: 'ORG10', name: 'Amberstone Warehousing', type: 'ORGANIZATION', subtitle: 'Faridabad', riskScore: 75 },
  'CASE01': { id: 'CASE01', name: 'Theft Case (CASE01)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE02': { id: 'CASE02', name: 'Fraud Case (CASE02)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE03': { id: 'CASE03', name: 'Missing Property Case (CASE03)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE04': { id: 'CASE04', name: 'Vehicle Related Case (CASE04)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE05': { id: 'CASE05', name: 'Cyber Related Case (CASE05)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE06': { id: 'CASE06', name: 'Financial Irregularity Case (CASE06)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE07': { id: 'CASE07', name: 'Theft Case (CASE07)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE08': { id: 'CASE08', name: 'Vehicle Related Case (CASE08)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE09': { id: 'CASE09', name: 'Organized Activity Case (CASE09)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE10': { id: 'CASE10', name: 'Missing Property Case (CASE10)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE11': { id: 'CASE11', name: 'Unidentified Incident Case (CASE11)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE12': { id: 'CASE12', name: 'Organized Activity Case (CASE12)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'CASE13': { id: 'CASE13', name: 'Financial Irregularity Case (CASE13)', type: 'CASE', subtitle: 'CASE', riskScore: 90 },
  'ACC05': { id: 'ACC05', name: 'Metro Cooperative Bank (Monika - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC13': { id: 'ACC13', name: 'State Trust Bank (Konkana - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC01': { id: 'ACC01', name: 'Metro Cooperative Bank (Garima - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC02': { id: 'ACC02', name: 'City Savings Bank (Sneha - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC03': { id: 'ACC03', name: 'State Trust Bank (Omkar - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC04': { id: 'ACC04', name: 'Regional Growth Bank (Sneha - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC06': { id: 'ACC06', name: 'Union Horizon Bank (Anand - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC07': { id: 'ACC07', name: 'State Trust Bank (Anand - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC08': { id: 'ACC08', name: 'National Bridge Bank (Surekha - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC09': { id: 'ACC09', name: 'City Savings Bank (Payal - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC10': { id: 'ACC10', name: 'City Savings Bank (Sonali - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC11': { id: 'ACC11', name: 'National Bridge Bank (Vinay - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC12': { id: 'ACC12', name: 'National Bridge Bank (Ajay - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC14': { id: 'ACC14', name: 'Metro Cooperative Bank (Madhav - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC15': { id: 'ACC15', name: 'Regional Growth Bank (Kali - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC16': { id: 'ACC16', name: 'State Trust Bank (Suraj - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC17': { id: 'ACC17', name: 'City Savings Bank (Kareena - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC18': { id: 'ACC18', name: 'City Savings Bank (Kareena - Business)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC19': { id: 'ACC19', name: 'Metro Cooperative Bank (Dia - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC20': { id: 'ACC20', name: 'Union Horizon Bank (Esha - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC21': { id: 'ACC21', name: 'National Bridge Bank (Madhavi - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC22': { id: 'ACC22', name: 'Regional Growth Bank (Geeta - Savings)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC23': { id: 'ACC23', name: 'Regional Growth Bank (Kartik - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC24': { id: 'ACC24', name: 'State Trust Bank (Leela - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC25': { id: 'ACC25', name: 'National Bridge Bank (Kartik - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC26': { id: 'ACC26', name: 'State Trust Bank (Payal - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
  'ACC27': { id: 'ACC27', name: 'Metro Cooperative Bank (Umesh - Current)', type: 'BANK ACCOUNT', subtitle: 'BANK ACCOUNT', riskScore: 70 },
};

export function getCanonicalEntity(id: string): CanonicalEntity | undefined {
  return CANONICAL_ENTITIES[id];
}

export function getEntityDisplayName(idOrNode: any): string {
  if (!idOrNode) return 'Unknown';
  if (typeof idOrNode === 'string') {
    const found = CANONICAL_ENTITIES[idOrNode];
    if (found) return found.name;
    return idOrNode;
  }
  const id = idOrNode.id || idOrNode.entityId;
  const canonical = id ? CANONICAL_ENTITIES[id] : undefined;
  if (canonical) {
    const currentName = idOrNode.name || idOrNode.entityName;
    if (!currentName || currentName === id || /^Phone\s+PH/i.test(currentName) || /^Vehicle\s+VH/i.test(currentName) || /^Case\s+CASE/i.test(currentName) || /^Location\s+LOC/i.test(currentName) || /^Account\s+ACC/i.test(currentName)) {
      return canonical.name;
    }
    return currentName;
  }
  return idOrNode.name || idOrNode.entityName || id || 'Unknown';
}
